name: Cancel Running Jobs

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  cancel-jobs:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to cancel workflows
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Cancel Running Workflows
        env:
          REPO: ${{ github.repository }}
        run: |
          gh api -X GET /repos/${REPO}/actions/runs --paginate | jq -r '.workflow_runs[] | select(.status == "in_progress") | .id' | while read run_id; do
            echo "Canceling workflow run ID: $run_id"
            gh api -X POST /repos/${REPO}/actions/runs/$run_id/cancel
          done