name: Manual 26 Triggers

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:      # Allow manual trigger

jobs:
  manual-26-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - name: trigger screen stocks with every letter of the alphabet
        uses: actions/github-script@v6
        with:
          script: |
            const alphabet = 'yz';
            const promises = alphabet.split('').map(async (char) => {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update_data.yml',
                ref: 'main',
                inputs: { char }
              });
            });
            
            await Promise.all(promises);
            
            async function sleep(ms) {
              return new Promise(resolve => setTimeout(resolve, ms));
            }
            
            async function checkWorkflowsCompletion() {
              let incompleteRuns = [];
              do {
                await sleep(1000);
                const runsResponse = await github.rest.actions.listWorkflowRunsForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  per_page: 100,
                  workflow_id: 'update_data.yml'
                });
                // Access the workflow runs from runsResponse.data.workflow_runs
                const workflowRuns = runsResponse.data.workflow_runs;
                console.log("Total workflow runs:", workflowRuns.length);
                incompleteRuns = workflowRuns.filter(run =>
                  run.status !== 'completed' && run.id !== context.runId
                );
                console.log("Incomplete runs:", incompleteRuns.length);
              } while (incompleteRuns.length > 0);
            
              console.log('done');
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update_relative_strength.yml',
                ref: 'main'
              });
            }
            
            await checkWorkflowsCompletion();
