name: Manual 26 triggers

on:
  # push:
  # branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:      # Allow manual trigger
  workflow_run:
    workflows: [ 'Calculate Relative Strength' ]
    types: [ completed ]

jobs:
  manual-26-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - name: trigger screen stocks with every letter of the alphabet
        uses: actions/github-script@v6
        with:
          script: |
            const alphabet = 'abcdefghijklmnopqrstuvwxyz';
            const promises = alphabet.split('').map(async (char) => {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update-data.yml',
                ref: 'main',
                inputs: {
                  char: char
                }
              });
              await new Promise(resolve => setTimeout(resolve, 5000));
            });
            
            await Promise.all(promises);
            
            await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update_relative_strength.yml',
                ref: 'main'
              });