name: Update data

on:
  # push:
  # branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:      # Allow manual trigger
    inputs:
      char:
        description: 'Character input for the script'
        required: true
        default: 'a'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # aggregate current data
        run: |
          python -m pip install -r requirements.txt
          python ../script/rs_data.py ${{ github.event.inputs.char }}

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stocks data [automated]"
          git pull --rebase 
          sleep 5
          for i in {1..5}; do
            git push && break || echo "Push failed, retrying ($i/10)..."
            sleep 5
            git pull --rebase 
          done
          git push
